from enum import StrEnum


class StageVersion(StrEnum):
    V0 = "V0"
    V1 = "V1"
    V2 = "V2"
    V3 = "V3"
    V4 = "V4"
    V5 = "V5"


class EvidenceClass(StrEnum):
    PUBLIC_FACT = "PUBLIC_FACT"
    PUBLIC_DERIVED = "PUBLIC_DERIVED"
    BENCHMARK_PRIOR = "BENCHMARK_PRIOR"
    ANALYST_ASSUMPTION = "ANALYST_ASSUMPTION"
    MANAGEMENT_RESPONSE = "MANAGEMENT_RESPONSE"
    CONTRACT = "CONTRACT"
    INVOICE = "INVOICE"
    SERVICE_ORDER = "SERVICE_ORDER"
    CIRCUIT_INVENTORY = "CIRCUIT_INVENTORY"
    HIGH_LEVEL_ARCHITECTURE = "HIGH_LEVEL_ARCHITECTURE"
    TOPOLOGY = "TOPOLOGY"
    TELEMETRY = "TELEMETRY"
    INCIDENT = "INCIDENT"
    UTILIZATION = "UTILIZATION"
    SERVICEABILITY = "SERVICEABILITY"
    MARKET_QUOTE = "MARKET_QUOTE"
    MARKET_BID = "MARKET_BID"
    REALIZED_INVOICE = "REALIZED_INVOICE"
    DISCONNECT_EVIDENCE = "DISCONNECT_EVIDENCE"


class ExecutionMode(StrEnum):
    LIVE = "LIVE"
    MOCK = "MOCK"
    REPLAY = "REPLAY"
    DETERMINISTIC_ONLY = "DETERMINISTIC_ONLY"


class ValueStatus(StrEnum):
    OBSERVED = "OBSERVED"
    DERIVED = "DERIVED"
    BENCHMARKED = "BENCHMARKED"
    ASSUMED = "ASSUMED"
    CARRIED_FORWARD = "CARRIED_FORWARD"
